data:
    scale_factor: 4
    upsample_LR_patch: False
    train:
        name: 'T91'
        data_dir: './preprocessed/T91_HR_32_EEE4423.npy'
        params:
            original_data_dir: '../../dataset/taskwise/super_resolution/T91/'
            patch_size: 32
            stride: 21
    valid:
        name:
            - 'Set5'
            - 'Set14'
            - 'Manga109'
            - 'BSDS100'
            - 'Urban100'
        base_dir: '../../dataset/taskwise/super_resolution/'


train:
    batch_size: 20
    num_epochs: 50
    dir: './results/dbpn.scale4'


model:
    name: 'dbpn'
    params:
        scale_factor: 4


scheduler:
    name: 'step'
    params:
      step_size: 5


optimizer:
    name: 'adam'
    params:
      lr: 0.0001
    gradient_clip: 0.01


loss:
    name: 'mse_loss'
    params:
      reduction: 'sum'


gpu: 1

