data:
    scale_factor: 2
    upsample_LR_patch: False 
    train:
        name: 'T91'
        data_dir: './preprocessed/T91_HR_64_EEE4423.npy'
        params:
            original_data_dir: '../../dataset/taskwise/super_resolution/T91/'
            patch_size: 64
            stride: 64
    valid:
        name:
            - 'Set5'
            - 'Set14'
            - 'Manga109'
            - 'BSDS100'
            - 'Urban100'
        base_dir: '../../dataset/taskwise/super_resolution/'


train:
    batch_size: 64
    num_epochs: 100
    dir: './results/fsrcnn.scale2.bandpass'
    
model:
    name: 'fsrcnn'
    params:
        scale_factor: 2

loss:
    name: 'mse_loss'
    params:
        reduction: 'mean'


transform:
    name: 'bandpass_transform'
    params:
        transform_ratio: 0.1

gpu: 1

