data:
    scale_factor: 4
    upsample_LR_patch: False 
    train:
        name: 'T91'
        data_dir: './preprocessed/T91_HR_40_EEE4423.npy'
        params:
            original_data_dir: '../../dataset/taskwise/super_resolution/T91/'
            patch_size: 40
            stride: 30
    valid:
        name:
            - 'Set5'
            - 'Set14'
            - 'Manga109'
            - 'BSDS100'
            - 'Urban100'
        base_dir: '../../dataset/taskwise/super_resolution/'


train:
    batch_size: 16
    num_epochs: 1000
    dir: './results/srfbn.scale4.bandpass'


model:
    name: 'srfbn'
    params:
        scale_factor: 4


scheduler:
    name: 'step'
    params:
      gamma: 0.5
      step_size: 200


optimizer:
    name: 'adam'
    params:
      lr: 0.0001


loss:
    name: 'mse_loss'
    params:
      reduction: 'sum'


transform:
    name: 'bandpass_transform'
    params:
        transform_ratio: 0.1



gpu: 1

